name: actions

run-name: Created by ${{ github.actor }}

on: [push]

jobs:

  tsc:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ github.event.pull_request.draft == false }}
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '16.17.1'
      - name: install package
        run: yarn install --immutable --immutable-cache --check-cache
      - name: type check
        run: yarn tsc --noEmit
  
